import ChangePassword from "./ChangePassword";

export const metadata = {
	title: "Change password | Passify",
	description: "Generated by create next app",
};

const page = () => {
	return <ChangePassword />;
};

export default page;
