import EditProfile from "./EditProfile";

export const metadata = {
	title: "Edit profile | Passify",
	description: "Generated by create next app",
};

const page = () => {
	return <EditProfile />;
};

export default page;
