import GetExeat from "./GetExeat";

export const metadata = {
	title: "Get exeat | Passify",
	description: "Generated by create next app",
};

const page = () => {
	return <GetExeat />;
};

export default page;
