import ResetPassword from "./ResetPassword";

export const metadata = {
	title: "Reset password | Passify",
	description: "Generated by create next app",
};

const page = () => {
	return <ResetPassword />;
};

export default page;
