import { Plus_Jakarta_Sans } from "next/font/google";
import "../styles/style.css";

const plusJakartaSans = Plus_Jakarta_Sans({
	weight: ["400"],
	subsets: ["latin"],
});

export const metadata = {
	title: "Passify",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={plusJakartaSans.className}>{children}</body>
		</html>
	);
}
