import Profile from "./Profile";

export const metadata = {
	title: "Profile | Passify",
	description: "Generated by create next app",
};

const page = () => {
	return <Profile />;
};

export default page;
