import ExeatDetails from "./ExeatDetails";

export const metadata = {
	title: "Exeat details | Passify",
	description: "Generated by create next app",
};

const page = () => {
	return <ExeatDetails />;
};

export default page;
