import PageHistory from "./History";

export const metadata = {
	title: "History | Passify",
	description: "Generated by create next app",
};

const page = () => {
	return <PageHistory />;
};

export default page;
