import SuccessExeat from "./SuccessExeat";

export const metadata = {
	title: "Success exeat | Passify",
	description: "Generated by create next app",
};

const page = () => {
	return <SuccessExeat />;
};

export default page;
