import AdminStudent from "./AdminStudent";

export const metadata = {
	title: "Student | Passify",
	description: "Generated by create next app",
};

const page = () => {
	return <AdminStudent />;
};

export default page;
