import AdminExeatDetails from "./AdminExeatDetails";

export const metadata = {
	title: "Exeat details | Passify",
	description: "Generated by create next app",
};

const page = () => {
	return <AdminExeatDetails />;
};

export default page;
