import AdminAllRequests from "./AdminAllRequests";

export const metadata = {
	title: "All requests | Passify",
	description: "Generated by create next app",
};

const page = () => {
	return <AdminAllRequests />;
};

export default page;
