import AdminApprovedRequests from "./AdminApprovedRequests";

export const metadata = {
	title: "Approved requests | Passify",
	description: "Generated by create next app",
};

const page = () => {
	return <AdminApprovedRequests />;
};

export default page;
