import AdminAllStudents from "./AdminAllStudents";

export const metadata = {
	title: "All students | Passify",
	description: "Generated by create next app",
};

const page = () => {
	return <AdminAllStudents />;
};

export default page;
