import Dashboard from "./Dashboard";

export const metadata = {
	title: "Dashboard | Passify",
	description: "Generated by create next app",
};

const page = () => {
	return <Dashboard />;
};

export default page;
