import AdminPendingRequests from "./AdminPendingRequests";

export const metadata = {
	title: "Pending requests | Passify",
	description: "Generated by create next app",
};

const page = () => {
	return <AdminPendingRequests />;
};

export default page;
