import { Suspense } from "react";
import UpdatePassword from "./UpdatePassword";

export const metadata = {
	title: "Update password | Passify",
	description: "Generated by create next app",
};

const page = () => {
	return (
		<Suspense fallback={<>Loading...</>}>
			<UpdatePassword />
		</Suspense>
	);
};

export default page;
