import UpdatePassword from "./UpdatePassword";

export const metadata = {
	title: "Update password | Passify",
	description: "Generated by create next app",
};

const page = () => {
	return <UpdatePassword />;
};

export default page;
