import AdminRejectedRequests from "./AdminRejectedRequests";

export const metadata = {
	title: "Rejected requests | Passify",
	description: "Generated by create next app",
};

const page = () => {
	return <AdminRejectedRequests />;
};

export default page;
